spring:
  application:
    name: hydra-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hydra?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "mysql@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  error:
    include-message: always

hydra:
  jwt:
    secret: 9a67471a7f76e73b22b2b1a13a89bc6a987d6545217983ea1c9b68e9860b73c4 # 256-bit AES key
    expiration-ms: 86400000 # 24 hours
  webpush:
    public-key: BIPD4fM8L2qP2WzN8mYt9fL7S9vP8uR7tB9vY2Q4W5vE8xM9yZ8aB7c4e5r6t7y8u9i0o1p2a3s4d5f6g7h8j
    private-key: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
    subject: mailto:support@hydra.com

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
